/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BrainModelGLB({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/BrainModel.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes['Node_#0'].geometry} material={materials.Translucent} position={[0, 0.04, 0]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/BrainModel.glb')
