/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/BrainModel.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <mesh
          name="Node_#0"
          castShadow
          receiveShadow
          geometry={nodes["Node_#0"].geometry}
          material={materials.Translucent}
          position={[0, 0.04, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          userData={{ name: "Node #0" }}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/BrainModel.gltf");
