/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function LargeCortexModelGLB({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/mediumModel.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.01, -0.01, 0]} scale={0}>
        <mesh geometry={nodes['mid-Mat'].geometry} material={materials.Mat} />
      </group>
      <group position={[-0.01, -0.01, 0]} scale={0}>
        <mesh geometry={nodes.Occipital_lope.geometry} material={materials.Mat} />
        <mesh geometry={nodes.Temporal_lope.geometry} material={materials.Mat} />
        <mesh geometry={nodes.Parietal_lope.geometry} material={materials.Mat} />
        <mesh geometry={nodes.Frontal_lope.geometry} material={materials.Mat} />
        <mesh geometry={nodes.mid_down.geometry} material={materials.Mat} />
      </group>
      <group position={[0.01, -0.01, 0]} scale={0}>
        <mesh geometry={nodes.Occipital_lope_1.geometry} material={materials.Mat} />
        <mesh geometry={nodes.Temporal_lope_1.geometry} material={materials.Mat} />
        <mesh geometry={nodes.Parietal_lope_1.geometry} material={materials.Mat} />
        <mesh geometry={nodes.Frontal_lope_1.geometry} material={materials.Mat} />
        <mesh geometry={nodes.mid_down_1.geometry} material={materials.Mat} />
      </group>
      <mesh geometry={nodes.Spinal_cord.geometry} material={materials.Mat} position={[0, -0.01, 0]} scale={0} />
      <mesh geometry={nodes.Cerebellum.geometry} material={materials.Mat} position={[0, -0.01, 0]} scale={0} />
    </group>
  )
}

useGLTF.preload('/mediumModel.glb')
